skip_window: 5
# neg_samples works slightly differently than uniform (3/4 power), so the approx. using
# SPMI will be off, especially when it is large. Usually neg_samples <= 4 gives accurate results.
# neg_samples between 1-5 is suggested (Mikolov et al)
neg_samples: 1
vocabulary_size: 10000
min_count: 100
